# Generated by Django 3.1 on 2020-08-12 20:31

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Введите название статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания статьи')),
                ('image', models.ImageField(blank=True, upload_to=blog.models.get_timestamp_path, verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_date'],
            },
        ),
    ]
